/// Research tree materials in **linear index order** (0 = bottom-left pair start, 30 = apex).
///
/// Matches rows bottom → top: 16 + 8 + 4 + 2 + 1 = 31 slots.
enum ResearchMaterialId {
  energyCore,
  heatShard,
  frostCrystal,
  steamEssence,
  magneticOre,
  lightFragment,
  crystalChunk,
  molecularGel,
  bacterialSample,
  dnaStrand,
  bloodDrop,
  bioMass,
  radiationDust,
  uraniumCore,
  plasmaOrb,
  darkMatterFragment,
  thermalCore,
  phaseCrystal,
  photonCore,
  structuredMatter,
  synapticLattice,
  organicCore,
  nuclearMass,
  voidPlasma,
  entropyCore,
  quantumMatrix,
  primalOrganism,
  annihilationCore,
  realityEngine,
  abyssalHeart,
  bloodstoneOfDominion,
}
