import 'package:flutter/material.dart';
import 'package:idle_laboratory/core/theme/app_color.dart';

class AppTheme {
  AppTheme._();

  static ThemeData get defaultTheme => _base(
        AppColor(
          primary: DefaultColor.primary,
          secondary: DefaultColor.secondary,
          accent: DefaultColor.accent,
          primaryText: DefaultColor.primaryText,
          background: DefaultColor.background,
          drawerBackground: DefaultColor.drawerBackground,
          titleText: DefaultColor.titleText,
          green: DefaultColor.green,
          sectionBorder: DefaultColor.sectionBorder,
          sectionGradient: DefaultColor.sectionGradient,
          cellBodyGradient: DefaultColor.cellBodyGradient,
          cellTopCapGradient: DefaultColor.cellTopCapGradient,
          cellBottomCapGradient: DefaultColor.cellBottomCapGradient,
          cellTopRimGradient: DefaultColor.cellTopRimGradient,
          cellBottomRimGradient: DefaultColor.cellBottomRimGradient,
          energyFillGradient: DefaultColor.energyFillGradient,
          energyGlowGradient: DefaultColor.energyGlowGradient,
          energyLightningColor: DefaultColor.energyLightningColor,
          energyParticleColor1: DefaultColor.energyParticleColor1,
          energyParticleColor2: DefaultColor.energyParticleColor2,
          heatFillGradient: DefaultColor.heatFillGradient,
          heatGlowGradient: DefaultColor.heatGlowGradient,
          heatChunkColor: DefaultColor.heatChunkColor,
          heatEmberColor1: DefaultColor.heatEmberColor1,
          heatEmberColor2: DefaultColor.heatEmberColor2,
          iceFillGradient: DefaultColor.iceFillGradient,
          iceGlowGradient: DefaultColor.iceGlowGradient,
          iceCrystalColor: DefaultColor.iceCrystalColor,
          iceParticleColor1: DefaultColor.iceParticleColor1,
          iceParticleColor2: DefaultColor.iceParticleColor2,
          steamFillGradient: DefaultColor.steamFillGradient,
          steamGlowGradient: DefaultColor.steamGlowGradient,
          steamVaporColor: DefaultColor.steamVaporColor,
          steamParticleColor1: DefaultColor.steamParticleColor1,
          steamParticleColor2: DefaultColor.steamParticleColor2,
          lightFillGradient: DefaultColor.lightFillGradient,
          lightGlowGradient: DefaultColor.lightGlowGradient,
          lightBeamColor: DefaultColor.lightBeamColor,
          lightParticleColor1: DefaultColor.lightParticleColor1,
          lightParticleColor2: DefaultColor.lightParticleColor2,
          molecularFillGradient: DefaultColor.molecularFillGradient,
          molecularGlowGradient: DefaultColor.molecularGlowGradient,
          molecularAtomColor: DefaultColor.molecularAtomColor,
          molecularBondColor: DefaultColor.molecularBondColor,
          molecularParticleColor1: DefaultColor.molecularParticleColor1,
          molecularParticleColor2: DefaultColor.molecularParticleColor2,
          bacterialFillGradient: DefaultColor.bacterialFillGradient,
          bacterialGlowGradient: DefaultColor.bacterialGlowGradient,
          bacterialOrganismColor: DefaultColor.bacterialOrganismColor,
          bacterialParticleColor1: DefaultColor.bacterialParticleColor1,
          bacterialParticleColor2: DefaultColor.bacterialParticleColor2,
          bloodFillGradient: DefaultColor.bloodFillGradient,
          bloodGlowGradient: DefaultColor.bloodGlowGradient,
          bloodCellColor: DefaultColor.bloodCellColor,
          bloodParticleColor1: DefaultColor.bloodParticleColor1,
          bloodParticleColor2: DefaultColor.bloodParticleColor2,
          bioFillGradient: DefaultColor.bioFillGradient,
          bioGlowGradient: DefaultColor.bioGlowGradient,
          bioSporeColor: DefaultColor.bioSporeColor,
          bioParticleColor1: DefaultColor.bioParticleColor1,
          bioParticleColor2: DefaultColor.bioParticleColor2,
          radiationFillGradient: DefaultColor.radiationFillGradient,
          radiationGlowGradient: DefaultColor.radiationGlowGradient,
          radiationWaveColor: DefaultColor.radiationWaveColor,
          radiationParticleColor1: DefaultColor.radiationParticleColor1,
          radiationParticleColor2: DefaultColor.radiationParticleColor2,
          plasmaFillGradient: DefaultColor.plasmaFillGradient,
          plasmaGlowGradient: DefaultColor.plasmaGlowGradient,
          plasmaFilamentColor: DefaultColor.plasmaFilamentColor,
          plasmaParticleColor1: DefaultColor.plasmaParticleColor1,
          plasmaParticleColor2: DefaultColor.plasmaParticleColor2,
          darkMatterFillGradient: DefaultColor.darkMatterFillGradient,
          darkMatterGlowGradient: DefaultColor.darkMatterGlowGradient,
          darkMatterSingularityColor: DefaultColor.darkMatterSingularityColor,
          darkMatterParticleColor1: DefaultColor.darkMatterParticleColor1,
          darkMatterParticleColor2: DefaultColor.darkMatterParticleColor2,
        ),
      );

  static ThemeData _base(AppColor color) => ThemeData(
        useMaterial3: false,
        extensions: [color],
        scaffoldBackgroundColor: color.background,
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(backgroundColor: color.primary),
        ),
      );
}
